editing_data_path = "../metrics/editing_metrics.tsv"
readers_data_path = "../metrics/readers_metrics.tsv"
unique_devices_data_path = "../metrics/regional_unique_devices.tsv"
geo_gap_path = "../metrics/geo_data_metrics.tsv"
gender_gap_path = "../metrics/gender_data_metrics.tsv"
save_directory = "../charts/"
author = "Movement Insights"