editing_data_path = "../metrics/editing_metrics.tsv"
readers_data_path = "../metrics/readers_metrics.tsv"
unique_devices_data_path = "../metrics/regional_unique_devices.tsv"
content_gap_data_path = "../metrics/content_gap_data_metrics.tsv"
save_directory = "../charts/"
author = "Movement Insights"